### ISSUE TITLE
Не работает /protect

### ISSUE THREAD

**Issue by ilitaI2P** [hoangpungnyuga/Echo#1]

**Comment by hoangpungnyuga** [comment]
Уверены что не работает? Лично у меня полностью всё работает.
Напишите более детально свою проблему, можете и приложить последние логи бота если там есть ошибка связанная с вашей проблемой.

**Comment by ilitaI2P** [comment]
![изображение](https://github.com/hoangpungnyuga/Echo/assets/81111889/b9c02887-3c30-47f8-9aad-b1728caccfd2)
![изображение](https://github.com/hoangpungnyuga/Echo/assets/81111889/7e35339e-f860-4c23-9e32-c4695af53c41)
![изображение](https://github.com/hoangpungnyuga/Echo/assets/81111889/d196ffe8-2467-4b23-b5a4-7fcd590c107d)
Бот даёт скринить и пересилать сообщения. логи пустые

**Comment by ilitaI2P** [comment]
Бот даёт скринить и пересилать сообщения

**Comment by ilitaI2P** [comment]
логи пустые

**Comment by hoangpungnyuga** [comment]
А, def protect ?
Ещё вы забыли добавить protect_content=protect(message) ниже.

**Comment by ilitaI2P** [comment]
def протект куда добавялять? protect_content=protect(message) добавлять нужно 2 раза?

**Comment by hoangpungnyuga** [comment]
Да, что это во втором даёт? Это даст то что ты не сможешь свои же сообщения копировать при условии что protect включен, если хочешь копировать свои же сообщения, но чтобы при этом другие не могли, достаточно сохранить как у тебя и есть.
![изображение](https://github.com/hoangpungnyuga/Echo/assets/94941278/e663b971-b681-4c53-9583-112e94afb3e6)

**Comment by ilitaI2P** [comment]
можно пожалуйста прислать код /profile c отображением protect?

**Comment by hoangpungnyuga** [comment]
Так как это буллевое значение, то там и добавлять нечего
{user.protect} вернёт True / False

К примеру
f"Копирование ваших сообщ.: {user.protect}"

**Comment by ilitaI2P** [comment]
![изображение](https://github.com/hoangpungnyuga/Echo/assets/81111889/6820890f-5245-41fe-8dd1-4264751281d4)

**Comment by hoangpungnyuga** [comment]
Я не читаю мысли, какой у вас код

**Comment by hoangpungnyuga** [comment]
Хотя профиль это уже отдельная тема, продолжим в лс? Пишите @wekosay

**Comment by ilitaI2P** [comment]
ооо, исправили ошибку, нужно было скобку перенести. благодарю за помощ
